fcitx/fcitx5

- src/lib/fcitx-utils/connectableobject.h
- src/lib/fcitx-utils/dbus/objectvtable.h
- src/lib/fcitx-utils/i18nstring.h
- src/lib/fcitx-utils/inputbuffer.h
- src/lib/fcitx-utils/library.h
- src/lib/fcitx-wayland/core/display.cpp
- src/lib/fcitx-wayland/core/display.h
- src/lib/fcitx-wayland/core/outputinformation.h
- src/modules/unicode/charselectdata.h
Add some missing includes which prevent the code from compiling using clang on FreeBSD.
> add missing includes

- src/server/CMakeLists.txt
Link with exeinfo if it was found.
> link to execinfo if found

- test/testevent.cpp
Check for empty read in testevent. For some event implementations, this means that the underlying object is closed. Also, add some debug information. Add 2 extra sources which can only be checked manually now.
> check for empty read in testevent and add extra debug info

- CMakeLists.txt
- src/lib/fcitx-utils/CMakeLists.txt
- src/lib/fcitx-utils/event_libevent.cpp
Use libevent for event loop.
* Change systemd to optional.
* Defer event and Exit event are simulated.
* EV_CLOSED is not used, because not all backends support it.
> Use libevent for event loop

- src/lib/fcitx-utils/standardpath.cpp
> Remove unreacheable break

- src/frontend/dbusfrontend/dbusfrontend.cpp
- src/lib/fcitx/inputcontext.cpp
- src/lib/fcitx/inputcontext.h
- src/lib/fcitx/userinterfacemanager.cpp
in preparation for fbterm support
> Implement client-side UI update dbus signal

- src/lib/fcitx/icontheme.cpp
https://github.com/qt/qtbase/commit/1c957bb8e57adf7674716f40b67c5d6877b32f86
Libc on alpha is too bad...
For #208
> Fix build on alpha

- CMakeLists.txt
- src/lib/fcitx-utils/misc.cpp
Fixes build on NetBSD and DragonFly BSD.
> Some *BSD build fix

- src/lib/fcitx-utils/fs.cpp
Given path `/storage/emulated/0/Android/data/fcitx5`, `makePath` would fail if `/storage/emulated` has permission `711`, because `isdir` requires the dir to be readable. But If you know the path, read permission for all parent directory is not necessary.
> Improve makePath, check dir exists before mkdir.

- src/lib/fcitx/misc_p.h
添加deepin桌面环境判断，
后面会有不同，
比如deepin中弹出的输入法配置界面会有不同，deepin中输入法配置界面会在控制中心中。
> Added deepin desktop environment judgment

- README.md
The current link in the README is dead, this one is not.
> Update dead Transifex link.

- src/lib/fcitx-utils/capabilityflags.h
- src/lib/fcitx/instance.cpp
> Add a new capability option to use the default layout IM when necessary.

- data/fcitx5-configtool.sh
same as fe927ae232a0955813e571a2e0be7e1f300df6ff for fcitx5-configtool
> fcitx5-configtool: which -> command -v

- src/im/keyboard/xkbrules.cpp
The characterData may not receive the full text at one time. Save text to buffer until endElement is called.
> Fix incorrect xkbrules parsing results

- src/modules/dbus/dbusmodule.cpp
Add group name and default input method in the fullInputMethodGroupInfo's return value
> Add two new fields in the dbus return value

- data/fcitx5-diagnose.sh
- src/lib/fcitx/misc_p.h
1. Added UKUI desktop environment in fcitx5-diagnose.sh
2. Added UKUI desktop environment judgment.
> Add UKUI desktop environment

- src/ui/classic/themes/default-dark/theme-dark.conf.in
- src/ui/classic/themes/default/theme.conf.in
1.If the default value is empty, it can be omitted. 
2.msgfmt would concatenate null values with the next row on earlier versions, which in turn would cause some problems.
> Delete the key whose value is empty.

- src/modules/spell/comp_spell_dict.cpp
Revert one file change in #957
> fix macos build

- src/lib/fcitx-utils/misc_p.h
- src/modules/clipboard/CMakeLists.txt
- src/modules/clipboard/clipboard.conf.in.in
- src/modules/clipboard/clipboard.cpp
- src/modules/clipboard/clipboard.h
- src/modules/clipboard/clipboardentry.h
- src/modules/clipboard/waylandclipboard.cpp
- src/modules/clipboard/waylandclipboard.h
- src/modules/clipboard/xcbclipboard.cpp
- src/modules/clipboard/xcbclipboard.h
- src/modules/xcb/xcbconvertselection.cpp
> Refactor clipboard code and add support for password manager hint

- src/lib/fcitx/instance.cpp
- src/lib/fcitx/instance_p.h
- src/server/errorhandler.cpp
- src/server/main.cpp
- src/ui/classic/plasmathemewatchdog.cpp
- src/ui/classic/plasmathemewatchdog.h
SIGKILL doesn't mean waitpid may immediate get any result.
> Use sigchld to clean up zombie process.

- src/lib/fcitx/instance.cpp
- src/lib/fcitx/instance.h
This may be a better alternative for system notification in lots of places.
> Add a new helper function to display custom input method information.

- src/lib/fcitx-utils/inputbuffer.h
close: https://github.com/fcitx/fcitx5/issues/1118
> include cstdint for GCC 15

- src/ui/classic/inputwindow.cpp
- src/ui/classic/waylandinputwindow.cpp
- src/ui/classic/xcbinputwindow.cpp
> Reset hover index when window is updated or hide

- src/lib/fcitx/instance.cpp
> disable zombie reaper on win32

- src/modules/wayland/waylandmodule.cpp
- src/modules/wayland/waylandmodule.h
Recently there was a misconfigured dependency on Arch in AUR's sdl package,
that may accidentually make AUR user poll in fcitx onto their system.
Which causes a lot of confusion for KDE users.
Since we now have selfDiagnose() on wayland, it is actually asking user
to be aware they're configuring fcitx in kde's system settings. If user
does not follow the guide, we'd assume user may not want to use fcitx to
avoid accidentally override user's keyboard config.
On arch there was also fcitx5's xdg autostart enabled, so it's very
likely if user installed it will be run by default.
> Only set layout to kde config if zwp_input_method_v1 is available a.k.a it is the chosen input method under virtual keyboard.

- src/frontend/fcitx4frontend/fcitx4frontend.cpp
- src/frontend/fcitx4frontend/fcitx4frontend.h
- src/frontend/ibusfrontend/ibusfrontend.cpp
- src/frontend/xim/xim.cpp
- src/frontend/xim/xim.h
- src/lib/fcitx-config/marshallfunction.cpp
- src/lib/fcitx-utils/dbus/libdbus/bus.cpp
- src/lib/fcitx-utils/environ.cpp
- src/lib/fcitx-utils/environ.h
- src/lib/fcitx-utils/key.cpp
- src/lib/fcitx-utils/log.cpp
- src/lib/fcitx/misc_p.h
- src/modules/wayland/waylandmodule.cpp
- src/modules/xcb/xcbkeyboard.cpp
- src/modules/xcb/xcbmodule.cpp
- src/tools/wayland-launcher.cpp
- src/ui/classic/buffer.cpp
- src/ui/classic/waylandcursortheme.cpp
- src/ui/classic/xcbui.cpp
getenv -> getEnvironment
stoi -> from_chars
> New API refactor

- src/modules/unicode/charselectdata.cpp
Update ranges for CJK UNIFIED IDEOGRAPH and TANGUT IDEOGRAPH from UnicodeData.txt of latest Unicode (16).
> fix Unicode ranges for ideographs

- src/frontend/dbusfrontend/dbusfrontend.cpp
wayland的应用，如果在候选词窗口（client side ui）显示时点击虚拟键盘，候选词窗口不会消失
> fix(wayland):Candidate word panel fails to hide upon virtual keyboard display
