src/modules/spell/spell-custom-dict.cpp
src/modules/spell/spell-enchant.cpp
src/modules/spell/spell-enchant.h

Fix the include path of enchant. If you check other users of enchant (https://github.com/GNOME/gspell/blob/a04b0a8b96b2a928cad2c368bc8495edcad8cb3a/gspell/gspell-checker.h, https://sourceforge.net/p/gtkspell/gtkspell/ci/master/tree/gtkspell/gtkspell.c), you'll find out that they use `#include <enchant.h>`

fix enchant's include path

---

src/lib/fcitx-utils/event.h
src/lib/fcitx-utils/utf8.h
src/lib/fcitx/candidatelist.cpp

https://gcc.gnu.org/gcc-10/porting_to.html
`<stdexcept>` is no longer included by default.

Porting to gcc-10

---

src/ui/classic/waylandeglwindow.cpp

测试环境：Gentoo
最新commit无法编译，Clang 10及GCC 9.3.0均报错
错误信息见https://pastebin.ubuntu.com/p/snk3TX6t72/
另外`fcitx5-chinese-addons`也有一个相关的编译错误，貌似是`UniqueCPtr`没有定义，见https://pastebin.ubuntu.com/p/ZYgMQS2Dz5/

Fix UniqueCPtr build error

---

src/lib/fcitx/icontheme.cpp
src/lib/fcitx/icontheme.h

同 #127 。
接着编译 `im module` 去了，鬼知道还有多少这种写法...

Replace "uint" with "unsigned int" in order to support musl libc

---

src/modules/imselector/imselector.cpp
src/modules/imselector/imselector.h

The module allows users to config hotkeys to switch to the 1-5th input method globally/locally.
Functionality is manually verified on my local machine.

Add a module that switches to the Nth input method via Hotkey

---

data/CMakeLists.txt

see https://cmake.org/cmake/help/v3.4/module/GNUInstallDirs.html
In case when `CMAKE_INSTALL_PREFIX=/usr`, `CMAKE_INSTALL_SYSCONFDIR` will be `/usr/etc`, which is weird.
While we can use `-DCMAKE_INSTALL_SYSCONFDIR=/etc` to workaround but `CMAKE_INSTALL_FULL_SYSCONFDIR` should be used in this case (which is `/etc` by default)

Fix default install path for autostart file

---

data/CMakeLists.txt
data/fcitx5-diagnose.sh

Some Linux distributions install libraries to multi-arch aware path, like /usr/lib/x86_64-linux-gnu/fcitx5

Config install path in fcitx5-diagnose when compile

---

src/lib/fcitx/icontheme.cpp

Fix a build failure due to missing headers on fedora rawhide (GCC 11 prerelease)
```
../src/lib/fcitx/icontheme.cpp: In member function 'std::string fcitx::IconThemePrivate::lookupIcon(const string&, int, int, const std::vector<std::__cxx11::basic_string<char> >&) const':
../src/lib/fcitx/icontheme.cpp:535:29: error: 'numeric_limits' is not a member of 'std'
535 |         auto minSize = std::numeric_limits<int>::max();
|                             ^~~~~~~~~~~~~~
```
[before](https://koji.fedoraproject.org/koji/taskinfo?taskID=56934740)
[after](https://koji.fedoraproject.org/koji/taskinfo?taskID=56934832)

add missing headers

---

src/lib/fcitx-utils/misc.cpp
src/lib/fcitx/icontheme.cpp

Add `getProcessName` support for Apple platform (BSD-like, but without libkvm).
Fix `modifiedTime` and explicitly export `std::timespec` from `struct timespec` on Apple platform.

Improve supports for Apple platform

---

src/lib/fcitx-utils/misc.cpp

On https://www.gnu.org/software/hurd/hurd/porting/guidelines.html
`__GNU__` can be used for GNU Hurd.
https://www.gnu.org/software/hurd/hurd/translator/procfs.html
And it has /proc/<pid/exe.
For #208

Fix build on GNU Hurd

---

src/frontend/waylandim/waylandimserver.cpp
src/frontend/waylandim/waylandimserverv2.cpp

This should fix one of the unexpected key inputs problem on sway:
https://github.com/swaywm/sway/issues/6193
The problem occurs as follows:
1. press Ctrl+d to exit from terminal emulator
2. fcitx captures the key press event and enables repeat timer
3. terminal emulator exits (while the key is still pressed)
4. fcitx sends key repeat events indefinitely (since there's no release event)
It's unclear whether this is a bug of the compositor (i.e. sway) or not, but
I think it's better for fcitx to not carry the key-repeat state over to new
keyboard grab.

Stop key repeat timer on wayland keyboard grab cleared

---

src/lib/fcitx/instance.cpp

Always return empty string when keyboard inputmethod is disabled, makes quickphrase and unicode addon works on Android.

Allow processComposeString when keyboard disabled.

---

src/lib/fcitx/addonloader.cpp
src/lib/fcitx/addonmanager.cpp

Addon authors can know if they made typo in their configure files, or packagers can know if they've forget to include some library files.
dummy.conf
```ini
[Addon]
Name=Dummy Addon
Type=SharedLibrary
Library=libdummy
Category=UI
Version=0.0.1
```
logs
```
E2021-11-18 19:56:34.028113 addonloader.cpp:32] Could not locate library libdummy.so for addon dummy.
I2021-11-18 19:56:34.028154 addonmanager.cpp:188] Could not load addon dummy
```

Improve logging for addon loading.

---

src/modules/unicode/CMakeLists.txt
src/modules/unicode/unicode.cpp
src/modules/unicode/unicode.h
src/modules/unicode/unicode_public.h

Allow triggering unicode input mode in other addons, for more convenient usage (namely on Android).

Export unicode addon's trigger function.

---

src/lib/fcitx-utils/dbus/libdbus/objectvtable_libdbus.cpp

One of my python script using glib and dbus suddenly stopped working today, complaining that the dbus method `State` of interface `org.fcitx.Fcitx.Controller1`'s signature doesn't match. It turns out that introspection xml is using wrong direction for returning values, and python is trying to validate parameters against the wrong signature.
This patch fixes the problem described above.
Tested on my system (Gentoo Linux, Sway).

fix dbus introspection bug

---

src/ui/classic/waylandinputwindow.cpp
src/ui/classic/waylandpointer.cpp
src/ui/classic/waylandpointer.h
src/ui/classic/waylandwindow.h

`WaylandWindow` has `click` event, but doesn't have `touch` event.
It is possible to add the event by using `WlSeat::getTouch`.
I understand that more implementation is needed to manage touch events in earnest,
but I think these modifications are necessary to make touch event work at least first.

Add touch event to WaylandWindow

---

src/lib/fcitx-utils/i18nstring.cpp

Android's bionic only supports 2 locales, `C` (aka `POSIX`) and `C.UTF-8` (aka `en_US.UTF-8`)
https://android.googlesource.com/platform/bionic/+/refs/tags/android-11.0.0_r48/libc/bionic/locale.cpp#50
... and would always return `C` or `C.UTF-8` when `setlocale(LC_*, nullptr)` is called.
https://android.googlesource.com/platform/bionic/+/refs/tags/android-11.0.0_r48/libc/bionic/locale.cpp#175
Here we override the value with env `FCITX_LOCALE`.

Read FCITX_LOCALE env for system locale on Android.

---

src/modules/spell/spell-enchant.cpp

It's a simple bug.
Because of this bug, the prediction candidates by `enchant` did not show up.
This fix makes the candidates to show up correctly.

Fix a problem where spellhint by enchant does not work

---

src/modules/spell/spell-enchant.cpp

I'm sorry.
The fix of https://github.com/fcitx/fcitx5/pull/417 causes a comparison warning.
```
warning: comparison of integer expressions of different signedness: ‘int’ and ‘size_t’
```
I have fixed this.

Fix comparison warning

---

src/lib/fcitx/globalconfig.cpp
src/lib/fcitx/globalconfig.h
src/lib/fcitx/instance.cpp

Changes below
https://github.com/fcitx/fcitx5/blob/09969b0982cca27a892c7bab17a1c33df435280f/src/lib/fcitx/instance.cpp#L1910-L1915
added in 217593a breaks building with `ENABLE_KEYBOARD=off` (namely on Android). Also those options seems useless without XKB.

Fix build with ENABLE_KEYBOARD=off.

---

src/im/keyboard/keyboard.cpp
src/im/keyboard/keyboard.h

Currently, we have to input `Control+Alt+H` to enable hint in KeyboardEngine.
I think it would be more useful if we could use hint by default in KeyboardEngine.
This fix adds `EnableHintByDefault` parameter to keyboard.conf.
By setting this parameter to `True`, we can use hint by default in KeyboardEngine.
~/.config/fcitx5/conf/keyboard.conf
```ini
EnableHintByDefault=True
```
I have confirmed this works correctly in keyboard-us.

Enable KeyboardEngine to use hint by default

---

src/lib/fcitx/inputmethodmanager.cpp
src/lib/fcitx/inputmethodmanager.h

Our virtual keyboard addon needs to simply enumerate the current IM group.
There is a switching language button, and we would like to enumerate the current IM group by pressing it.
I've sent a similar PR before: https://github.com/fcitx/fcitx5/pull/431
and I understand Fcitx5 has its own stacking style switching function to control the current IM group.
But how about just adding a function of simple enumeration to `InputMethodManager` for addons?

Add simple group enumerating function for addons

---

data/org.fcitx.Fcitx5.metainfo.xml.in

The content_rating tag is needed in order to pass validation with
appstream-util (appstream-glib).
Flathub CI builds are failing without this.
The tag is empty as no age restrictions are needed.

AppStream metainfo: Add content_rating tag

---

src/ui/classic/theme.h
src/ui/classic/xcbinputwindow.cpp

Support for configuring the overall position offset of the InputPanel.

add support of xcb input panel offset

---

src/lib/fcitx-utils/standardpath.cpp
test/testfs.cpp
test/teststandardpath.cpp

Remove trailing slash from dir paths before checking uniqueness. This fixes fcitx#519

Remove trailing slash from dir paths before checking uniqueness. Fix #519

---

src/ui/classic/classicui.cpp

If XCB module is disabled here, the fcitx5 server will SEGV.
It can be easily reproduced by:
1. disable XCB addon from fcitx5-configtool
2. use wayland and run sth like GTK_IM_MODULE=fcitx5 firefox
3. toggle the im, the fcitx5 server will crash

Bugfix: guard against disabled xcb module

---

src/ui/classic/classicui.h
src/ui/classic/inputwindow.cpp
src/ui/classic/inputwindow.h
src/ui/classic/waylandinputwindow.cpp
src/ui/classic/xcbinputwindow.cpp

There's currently DPI detection logic in XCB ui, but wayland applications need to handle DPI themselves, and this option is currently missing. On my 1080p screen, the wayland ui candidate box is too small, as it rendered in the default 96 dpi. I could workaround it by setting a huge font size, but that would also increase the candidate box size in qt & gtk.
This PR add an option to classicui configure section, setting a DPI separately for wayland ui.

Proposal: add option to change wayland ui resolution

---

src/frontend/dbusfrontend/dbusfrontend.cpp
src/lib/fcitx/inputcontext.cpp
src/lib/fcitx/inputcontext.h
src/lib/fcitx/inputcontext_p.h
src/lib/fcitx/instance.cpp
src/ui/virtualkeyboard/virtualkeyboard.cpp

1. In some GUI frameworks like Qt, it provides good support for virtual keyboard.
So Qt IM module has the need to disable the default behavior of virtual keyboard
when the object get focus or loses focus. Qt can decide if it should show virtual
keyboard when the object gets focus or hide virtual keyboard when the object loses
focus.
2. However, In some GUI frameworks like GTK, it provides poor support for virtual
keyboard. So It's necessary to show or hide virtual keyboard when the object get focus
or loses focus and this is the default behavior provided by fcitx5. Maybe in the future,
GTK may provide good support for virtual keyboard just as Qt does.

Control the behavior of virtual keyboard when the object gets focus or loses focus

---

src/frontend/dbusfrontend/dbusfrontend.cpp

1. If supportedCapability_ has no value, the bits in cap from 0bit to 39bit are effective.
2. Or else, the effective bits in cap will be determinded by the bits in supportedCapability_'s value.
3. For compatibility reason, to get new effective bits such as 40bit(Disable) or above, we should use supportedCapability_'s value to get all the effective bits in cap.

Use supportedCapability_'s value to get all the effective bits

---

src/frontend/dbusfrontend/dbusfrontend.cpp
src/lib/fcitx/inputcontext.cpp
src/lib/fcitx/inputcontext.h
src/lib/fcitx/inputcontext_p.h
src/lib/fcitx/instance.cpp

Use two separate options to control the behavior of virtual keyboard when the object gets focus or loses focus
In some GUI frameworks like Qt, it provides good support to show virtual keyboard and provides poor support to hide virtual keyboard. So Qt IM module has the need to disable the default behavior of virtual keyboard when the object get focus and enable the default behavior of virtual keyboard when the object loses focus. Qt can decide if it should show virtual keyboard when the object gets focus. However, fcitx will hide virtual keyboard when the object loses focus.

Use two separate options to control the behavior of virtual keyboard when the object gets focus or loses focus

---

src/modules/quickphrase/quickphrase.d/latex.mb

The correct abbreviation for `⊤` should be `\top`, instead of `\bot`. `\bot` should map to `⊥`.

Correct \bot in latex.mb

---

src/ui/kimpanel/kimpanel.conf.in.in
src/ui/kimpanel/kimpanel.cpp
src/ui/kimpanel/kimpanel.h

Hello everyone!
One thing I didn't like about the Kimpanel support was the use of the generic keyboard icons. So, as with the Classic User Inferface addon, I added an option to prefer text icons. Feedback is welcome!

Add text icon support for Kimpanel

---

src/lib/fcitx/event.cpp
src/lib/fcitx/event.h
src/lib/fcitx/instance.cpp
src/lib/fcitx/instance.h
src/lib/fcitx/instance_p.h
src/ui/virtualkeyboard/virtualkeyboard.cpp

1. There are two kinds of virtual keyboard at least.
2. The input method engine may support one or two function mode: full or limited.
a) The full function mode is the default function mode. All the input method engine
which does not implement InputMethodEngineV4 or its ascendants supports the full
function mode.
b) The limited function mode is a dedicated function mode which is used for the true
virtual keyboard. The input method engine which implements InputMethodEngineV4 or its
ascendants should tell fcitx which function mode it supports. That is, it may support
full function mode or limited function mode or both.
3. The two different virtual keyboard use different function mode of input method engine.
The virtual keyboard should tell fcitx which function mode it needs. Fcitx will …

 Optimize the support for virtual keyboard

---

src/modules/dbus/dbusmodule.cpp

If the argument is an empty string, it will use the current group name, or else it will use the argument as the group name.

Add a new dbus method to get input method entries by group name

---

src/ui/CMakeLists.txt

Enable virtualkeyboard ui only when dbus enabled

---

src/ui/virtualkeyboard/virtualkeyboard.cpp
src/ui/virtualkeyboard/virtualkeyboard.h

If the input method mode is PhysicalKeyboard, when we call the function VirtualKeyboardService::toggleVirtualKeyboard, we expect that it has the same effect as we call the function VirtualKeyboardService::showVirtualKeyboard. That is, the input method mode will be OnScreenKeyboard and the virtual keyboard will be visible.

The input method mode should be OnScreenKeyboard when toggling first

---

src/modules/quickphrase/quickphrase.cpp

Support InputContext::invokeAction and Home/End/Left/Right keys.
Since `state->reset(inputContext)` does reset `inputPanel` and `updateUserInterface`, duplicate operations were removed to reduce UI flicker.
Move `commitString` before `reset` also helps reduce flicker on Android, because [InputConnection#commitText](https://developer.android.com/reference/android/view/inputmethod/InputConnection#commitText(java.lang.CharSequence,%20int)) would replace any composing span on Android.

Implement cursor movement in quickphrase.

---

src/ui/classic/waylandinputwindow.cpp

Env: Ubuntu server 22.04 with gdm3 installed, running in VirtualBox.
Step to reproduce:
* Build and install fcitx5 as debug.
* Open 2 gnome-terminal.
* In one terminal, `fcitx5 --verbose *=5`
* When fcitx5 is ready, click the other terminal.
* Segfault.
[diagnose.txt](https://github.com/fcitx/fcitx5/files/12775477/diagnose.txt)

fix npe: switch between wayland gnome-terminal in debug mode

---

src/lib/fcitx/inputpanel.cpp
src/lib/fcitx/inputpanel.h
src/lib/fcitx/userinterfacemanager.cpp

If the virtual keyboard custom callback function is implemented, the data is updated to the virtual keyboard custom callback function first.

add virtualkeyboard custom input panel callback

---

cmake/Fcitx5CompilerSettings.cmake
src/frontend/CMakeLists.txt
src/frontend/xim/CMakeLists.txt
test/addon/CMakeLists.txt

* The linker options are not supported by the linker. Related: https://github.com/neovim/neovim/pull/23263
* Move `ENABLE_X11` to outer level as it makes no sense to generate `xim.conf`

Some changes regarding macOS build

---

src/lib/fcitx-utils/keydata.h
test/testkey.cpp

Use `_UCS_LESS_OR_EQUAL` instead of `_UCS_LESS` because there are already some duplication in `gdk_unicode_to_keysym_tab` and I don't know which entry to keep.

fix some unicode to keySym mapping

---

src/modules/spell/spell-custom-dict.cpp

Include `fcitx-utils/endian_p.h` where uses `le32toh`
https://github.com/fcitx/fcitx5/blob/2a9f7011a6b9eb01d66f50bcc8cfa41d2f732aef/src/modules/spell/spell-custom-dict.cpp#L93-L95
Closes #962

Fix build on Android

---

src/lib/fcitx-utils/cutf8.cpp
src/lib/fcitx-utils/cutf8.h
src/lib/fcitx-utils/i18n.cpp
src/lib/fcitx-utils/i18n.h

```
C:/Users/liumeo/github/fcitx5-windows/fcitx5/src/lib/fcitx-utils/cutf8.cpp:153:7: error: redeclaration of 'fcitx_utf8_get_char' cannot add 'dllexport' attribute
char *fcitx_utf8_get_char(const char *i, uint32_t *chr) {
^
C:/Users/liumeo/github/fcitx5-windows/fcitx5/src/lib/fcitx-utils/cutf8.h:26:7: note: previous declaration is here
char *fcitx_utf8_get_char(const char *in, uint32_t *chr);
^
```

move FCITXUTILS_EXPORT to headers

---

src/lib/fcitx-utils/standardpath.cpp

```
C:/Users/liumeo/github/fcitx5-windows/fcitx5/src/lib/fcitx-utils/standardpath.cpp:478:18: error: use of undeclared identifier 'O_ACCMODE'
if ((flags & O_ACCMODE) == O_WRONLY || (flags & O_ACCMODE) == O_RDWR) {
^
C:/Users/liumeo/github/fcitx5-windows/fcitx5/src/lib/fcitx-utils/standardpath.cpp:478:53: error: use of undeclared identifier 'O_ACCMODE'
if ((flags & O_ACCMODE) == O_WRONLY || (flags & O_ACCMODE) == O_RDWR) {
^
```
Some code from C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\ucrt\fcntl.h
```c
#define _O_RDONLY      0x0000  // open for reading only
#define _O_WRONLY      0x0001  // open for writing only
#define _O_RDWR        0x0002  // open for reading and writing
#define _O_APPEND      0x0008  // writes done at eof
...
#if (defined _CRT_DECLARE_NONSTDC_NAMES && …
```

define O_ACCMODE on windows

---

CMakeLists.txt
src/frontend/dbusfrontend/dbusfrontend.cpp
src/lib/fcitx/candidatelist.cpp
src/lib/fcitx/candidatelist.h
src/lib/fcitx/text.cpp
src/lib/fcitx/text.h
src/ui/classic/inputwindow.cpp
src/ui/kimpanel/kimpanel.cpp
src/ui/virtualkeyboard/virtualkeyboard.cpp
test/testcandidatelist.cpp
test/testtext.cpp

Currently comment of a rime candidate is [appended](https://github.com/fcitx/fcitx5-rime/blob/92a4410cfbcefd3782ec6b8efd54f9a071274f62/src/rimecandidate.cpp#L24-L27) into candidate in engine level, so it's hard to distinguish and apply different style.
The PR adds a new property to CandidateWord and preserves the behavior in 3 UI implementations (classicui and kimpanel tested, virtualkeyboard not tested).

add comment property to CandidateWord

---

CMakeLists.txt
cmake/FindIsoCodes.cmake
cmake/FindXKeyboardConfig.cmake

Allow overriding `ISOCODES_ISO639_JSON` `ISOCODES_ISO3166_JSON` `XKEYBOARDCONFIG_XKBBASE` and `XKEYBOARDCONFIG_DATADIR`.
Since the default rules file may be unavailable during build, the `FATAL_ERROR` loglevel is changed to `WARNING` as well.

Allow overriding iso-codes and xkb paths

---

src/lib/fcitx-utils/cutf8.cpp
src/lib/fcitx-utils/utf8.cpp
test/testkey.cpp
test/testutf8.cpp

Consider non-character as valid unicode

---

src/lib/fcitx/icontheme.cpp
test/testicontheme.cpp

Now we have a much of icons that uses "fcitx_" as the name, including mozc, skk, kkc, rime, to avoid xdg icon spec based fallback.
But we missed the flatpak naming mapping for those icons. Update the condition here, and also handle the special name "fcitx" (I don't think we do have code that uses "fcitx" as icon, but well.. )
https://github.com/fcitx/mozc/issues/53#issuecomment-2105739015

Fix icon name mapping in flatpak

---

src/frontend/waylandim/waylandimserver.cpp
src/frontend/waylandim/waylandimserverv2.cpp

Prototype of std::clamp is (val, lo, hi) while I assume it to be (lo, val, hi). This may trigger assertion if assertion is enabled.

Fix wrong usage of std::clamp.

---

src/lib/fcitx-utils/dbus/libdbus/objectvtable_libdbus.cpp

依据[官方标准](https://dbus.freedesktop.org/doc/dbus-specification.html#introspection-format)，\<signal\>下的\<arg\>不应有direction。这个attr给一些用于调试的外部工具，例如d-spy造成了解析错误

libdbus: <arg> for <signal> should not have directions

---

src/frontend/ibusfrontend/ibusfrontend.cpp
src/lib/fcitx-config/configuration.h
src/lib/fcitx-config/iniparser.cpp
src/lib/fcitx-config/iniparser.h
src/lib/fcitx-config/optiontypename.h
src/lib/fcitx-utils/standardpath.cpp
src/lib/fcitx-utils/standardpath.h
src/lib/fcitx/addoninfo.cpp
src/lib/fcitx/addoninfo.h
src/lib/fcitx/addonmanager.cpp
src/lib/fcitx/inputmethodmanager.cpp
src/modules/quickphrase/quickphraseprovider.cpp
src/modules/quickphrase/quickphraseprovider.h
test/teststandardpath.cpp

There is a risk that multiOpen open too many files at the same time and use all the fd. Should prefer the new locate over multiOpen. (#1052)

Add a new overload to locate and replace multiOpen with locate

---

CMakeLists.txt
src/lib/fcitx/action.cpp
src/lib/fcitx/action.h

It will be nice to show hotkey bound to actions in macOS menu like built-in Pinyin does.

add hotkey method to Action

---

src/frontend/xim/xim.cpp

Filter out button mask in XIM key state before sending it to XKB common

---

src/modules/notificationitem/notificationitem.cpp
src/modules/notificationitem/notificationitem.h
src/modules/notificationitem/notificationitem_public.h
src/ui/classic/xcbui.cpp
src/ui/classic/xcbui.h

Right now both virtual keyboard & classicui want SNI, but when transition 
between two UI, sni is disabled and then re-enabled which is causing XCB
tray window being show/hide immediately.
This change try to simplify the xcb tray window logic:
1. hide, if suspend()
2. If SNI addon is not available. show on resume
If SNI addon is available, defer 1sec and check SNI status.
SNI enable/disable logic is updated to allow multiple enable/disable by
using a reference counter. disable() is deferred with event dispatcher,
to avoid enable/disable causing register/unregistration.

Simplify the xcb tray window logic and avoid SNI transitional flicker between two UI

---

src/modules/spell/spell.cpp
src/modules/spell/spell.h

This enables including SpellModuleFactory on iOS to make a static addon.

move SpellModuleFactory to header

---

src/lib/fcitx-utils/misc.cpp

macro ref: https://github.com/xybp888/iOS-SDKs/blob/f5c585b443f1e0b5c6ced2732aac183e71021c86/iPhoneOS13.0.sdk/usr/include/TargetConditionals.h#L67

disable process functions on iOS

---

cmake/Fcitx5CompilerSettings.cmake

https://github.com/fcitx/libime/pull/81 introduces build time checking for `std::filesystem` by [check_cxx_source_compiles](https://cmake.org/cmake/help/latest/module/CheckCXXSourceCompiles.html), but it ([try_compile](https://cmake.org/cmake/help/latest/command/try_compile.html) actually) would ignore language standard setting variables. CMP0067 corrects such behavior.
https://cmake.org/cmake/help/latest/policy/CMP0067.html

Set CMake policy CMP0067 to NEW.

---

src/lib/fcitx-utils/misc.h

This is needed in engines so that
* Pthread could be disabled;
* By default cursor won't be pinned at the beginning of client preedit.

Add isEmscripten helper function

---

src/lib/fcitx/addonloader.cpp
src/lib/fcitx/addonloader_p.h
test/addon/CMakeLists.txt
test/addon/dummyaddondeps.cpp
test/addon2/fcitx5/addon/dummyaddon2.conf
test/testaddon.cpp

In general this is not very useful on linux, but for android where
LD_LIBRARY_PATH doesn't work, it can be used as an built-in linker to
load depenedency libraries.

Add support for shared addon loader to load multiple libraries

---

src/lib/fcitx/candidatelist.cpp

macOS built-in IM doesn't have the dot.

no default dot in candidate label on macOS

---

src/lib/fcitx/instance.cpp
src/lib/fcitx/instance_p.h
src/lib/fcitx/userinterfacemanager.cpp

1. When the user interacts with some applications rather than the virtual keyboard itself, the virtual keyboard should show or hide if it is enabled.
2. For example, if the user clicks a window and the window has a text input control which has the focus and accepts the input from the keyboard, then the virtual keyboard should show automatically if the auto show switch is enabled.
3. Then, if the window loses the focus, the virtual keyboard should hide automatically if the auto hide switch is enabled.

The virtual keyboard should show or hide automatically if enabled

---

src/ui/virtualkeyboard/virtualkeyboard.cpp
src/ui/virtualkeyboard/virtualkeyboard.h

If the virtual keyboard should not show automatically, then the input method mode should be set physical keyboard when the user closes the virtual  keyboard by interacting with the virtual keyboard itself. For example, if the user clicks a close button in the virtual keyboard or clicks an icon in the task bar or a float button on the desktop which can close the virtual keyboard, then the virtual keyboard will be closed and the input method mode should be set physical keyboard.

The input method mode should be set physical keyboard when necessary

---

src/lib/fcitx/globalconfig.cpp
src/lib/fcitx/globalconfig.h
src/lib/fcitx/instance.cpp
src/lib/fcitx/instance_p.h
test/CMakeLists.txt
test/testinstance.cpp

This is intended to solve some issue when user have other intentions.
For example, user may press "Shift" to do some text selection with
mouse. However, input method may not be capable (theoratically
possible on certain platform, but it's not implemented and not possible
on all platform) to detect user actually want to use mouse. If application
does not send "reset()", input method may wrongly trigger the action.
Some other cases include:
- Ctrl and scroll mouse
- user wants to type Shift+A, but regrets after press shift. So user
release all key but accidentally triggers "Shift" to switch input
method.
This is not perfect but should help solve some unintended action.

Add new global option to allow change the time limit on modifier only key triggering

---

src/ui/classic/xcbinputwindow.cpp

Pantheon has a bug that can't not display popup window under Xwayland
twice. While the bug is reported, it's not clear when it may be fixed.
Also, input method window is indeed more like a combo box and wmspec
mentioned that it's also a common override redirect. So try to use that
instead.
Workaround #1209

Use _NET_WM_WINDOW_TYPE_COMBO as input window type under X11.

---

src/modules/notificationitem/notificationitem.cpp

…other desktop environments in the future

optimize code

---

src/lib/fcitx-utils/semver.cpp

After [upgrading](https://github.com/fcitx-contrib/fcitx5-js/pull/19) emscripten to 4.0.0, fcitx5 failed to compile:
```
FAILED: fcitx5/src/lib/fcitx-utils/CMakeFiles/Fcitx5Utils.dir/semver.cpp.o 
/home/runner/work/fcitx5-js/fcitx5-js/emsdk/upstream/emscripten/em++ -DFCITX_GETTEXT_DOMAIN=\"fcitx5\" -DFMT_HEADER_ONLY=1 -DFcitx5Utils_EXPORTS -I/home/runner/work/fcitx5-js/fcitx5-js/build/fcitx5 -I/home/runner/work/fcitx5-js/fcitx5-js/fcitx5/src/lib/fcitx-utils/.. -I/home/runner/work/fcitx5-js/fcitx5-js/build/fcitx5/src/lib/fcitx-utils/.. -isystem /home/runner/work/fcitx5-js/fcitx5-js/build/sysroot/usr/include -Wall -Wextra  -O3 -DNDEBUG -std=c++17 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -fPIC -fexceptions -MD -MT fcitx5/src/lib/fcitx-utils/CMakeFiles/Fcitx5Utils.dir/semver.cpp.o …
```

fix: iterator is not pointer

---

src/modules/quickphrase/quickphrase.cpp
src/modules/quickphrase/quickphrase.h
src/modules/quickphrase/quickphrase_public.h
test/testquickphrase.cpp
testing/testfrontend/testfrontend_public.h

Whenever an input method want to temporarily enter quickphrase, we allow
quickphrase to restore to engine, if user change buffer into a specified
state.

Add a new API setBufferWithRestoreCallback to quickphrase

---

src/lib/fcitx-utils/fs.cpp
src/lib/fcitx-utils/mtime_p.h
src/lib/fcitx/icontheme.cpp

1. mtime uses st_mtime as fallback
2. fix mkdir
3. Effectively disable icon theme cache on windows, there's no tool generate cache anyway on windows. We may still need it to load icon.
Effectively disable icon theme cache on windows
Close #1245

Make fs.cpp compile on windows

---

src/lib/fcitx-utils/standardpath.cpp

C:/msys64/home/liumeo/github/fcitx5-windows/fcitx5/src/lib/fcitx-utils/standardpath.cpp:653:26: error: use of undeclared identifier 'utf8'
653 |             auto wfile = utf8::UTF8ToUTF16(file.tempPath());
|                          ^
1 error generated.

Add missing include utf8 in standardpath.cpp

---

src/ui/classic/classicui.cpp

The header may be not available when X11 is disabled. Fixes fcitx5 build without X11 libraries.
Fixes: e723881a ("Clang-tidy clean up for classic ui")

ui: classic: Include xcb/xcb.h only when X11 is enabled

---

src/lib/fcitx-utils/CMakeLists.txt

remove duplicated cutf8.h on install

---

src/im/keyboard/keyboard.cpp
src/lib/fcitx-utils/i18n.h
src/lib/fcitx-utils/misc_p.h
src/lib/fcitx/instance.cpp
src/modules/xcb/xcbconnection.cpp

While we can not check translated string, it is still make sense
to check the original string at compile time.
It also simplify the usage and solve the issue that runtime_format_string
is not available at c++20.

Remove formatUnchecked and extend i18n api with format check.

---

src/lib/fcitx/icontheme.cpp

Icon theme scale was incorrectly being assigned to size_ instead of scale_ when parsing Scale config option.

Fix icon theme scale parsing

---

src/lib/fcitx-utils/key.cpp
test/testinstance.cpp
test/testkey.cpp

If modifier-only key can be considered as two parts, modifier and
the trigger key. Trigger key's left and right should be considered when
checking isReleaseOfModifier().
Fix #1289

Correctly check left / right for modifier only key

---

src/modules/clipboard/clipboard.h

Improve the description of the password display option. The previous english description was the wrong way around, as it indicated that the password was only shown when the checkbox was checked.

clipboard: improve description of password display

---

.clang-format
src/lib/fcitx-utils/standardpath.cpp

The plan was to replace it with a new version of the class, but we want to make it compile.

Make standardpath compile on win32

---

src/lib/fcitx/misc_p.h

Enhance the desktop environment detection logic to include support for the Deepin desktop environment.

Add Deepin desktop environment detection

---

src/lib/fcitx-utils/standardpath.h
src/lib/fcitx-utils/standardpaths.cpp

Certain platform there might be overload function to ::open(), use a
template function to wrap it instead of using function pointer.
Otherwise we would need to write the full signature of open, which is
undesirable since certain platform may have non-standard signature.

Fix StandardPaths::openPath on certain platform

---

src/modules/quickphrase/quickphrase.d/emoji.mb

I was digging around and found this:
https://github.com/fcitx/fcitx5/blob/ebf24ddc8a2afe331df2b2f4cbe538f73a4a9b5f/src/modules/quickphrase/quickphrase.d/emoji.mb#L27
It looks like a typo rather than an intentional misspelling, so I went ahead and fixed it.

fix(emoji.mb): typo in quickphrase emoji
